//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeldridGen.Example.Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeldridGen.Example.Engine.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphicsDevice not initialised.
        /// </summary>
        internal static string DeviceUninitialized {
            get {
                return ResourceManager.GetString("DeviceUninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance can be registered per type / interface in a given exchange..
        /// </summary>
        internal static string ExchangeDoubleRegistration {
            get {
                return ResourceManager.GetString("ExchangeDoubleRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An output description must be specified when running headless (i.e. without a primary swapchain).
        /// </summary>
        internal static string PipelineNoOutputDesc {
            get {
                return ResourceManager.GetString("PipelineNoOutputDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load renderdoc.
        /// </summary>
        internal static string RenderDocFail {
            get {
                return ResourceManager.GetString("RenderDocFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpriteLease used after return.
        /// </summary>
        internal static string SpriteLeaseReused {
            get {
                return ResourceManager.GetString("SpriteLeaseReused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only sampled texture usage is currently supported (with optional mipmapping).
        /// </summary>
        internal static string TextureUsage {
            get {
                return ResourceManager.GetString("TextureUsage", resourceCulture);
            }
        }
    }
}
